# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: 
  vmImage: 'ubuntu-16.04'

trigger:
  batch: true
  branches:
    include: [ master ] # branch names which will trigger a build
  paths:
    include:  [ web/src/*, web/web-app-pipeline.yml, web/scripts/deploy-apps.ps1, web/build/*, web/deploy/deploy-apps.ps1 ] # file paths which must match to trigger a build

steps:
# PowerShell
# Run a PowerShell script on Windows, macOS, or Linux.
- task: PowerShell@2
  inputs:
    targetType: filePath # Optional. Options: filePath, inline
    filePath: ./web/scripts/deploy-apps.ps1 # Required when targetType == FilePath
    arguments:  -systemName $(systemName) -region $(region) -userName $(userName) -password $(password) -tenantId $(tenantId)
    errorActionPreference: stop # Optional. Options: stop, continue, silentlyContinue
    failOnStderr: false # Optional
    ignoreLASTEXITCODE: false # Optional
    pwsh: true # Optional
    workingDirectory: ./web/scripts # Optional